[package]
name = "launch"
version = "0.1.0"
edition = "2021"
license = "MIT"
description = "An experiment project to learn Rust. It opens apps."

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
